services:
  - type: web
    name: nutrition-analyzer-api
    env: python
    plan: free
    region: singapore
    rootDir: Flask
    buildCommand: ""
    startCommand: "python app.py"
    runtime: python
